### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by richwandell** [b12io/orchestra#57]
```
==> default: Cleaning up...
==> default: Downloading/unpacking orchestra
==> default:   Running setup.py (path:/tmp/pip_build_root/orchestra/setup.py) egg_info for package orchestra
==> default:     Traceback (most recent call last):
==> default:       File "<string>", line 17, in <module>
==> default:       File "/tmp/pip_build_root/orchestra/setup.py", line 3, in <module>
==> default:         from release import get_version
==> default:     ImportError: No module named 'release'
==> default:     Complete output from command python setup.py egg_info:
==> default:     Traceback (most recent call last):
==> default: 
==> default:   File "<string>", line 17, in <module>
==> default: 
==> default:   File "/tmp/pip_build_root/orchestra/setup.py", line 3, in <module>
==> default: 
==> default:     from release import get_version
==> default: 
==> default: ImportError: No module named 'release'
==> default: 
==> default: ----------------------------------------
==> default: Cleaning up...
==> default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/orchestra
==> default: Storing debug log for failure in /root/.pip/pip.log
```

**Comment by jrbotros** [comment]
Good catch, thanks so much! Looks like we forgot to include a file in the manifest, so setup.py errors out when it tries to import it :flushed: I made a quick fix and will push the updated version to pypi shortly!
